// Copies the build-generated data/*.json files into public/data/ so Next.js can serve
// them as static assets at the same /data/<file>.json URLs the client already expects.
// Runs before `next dev` and `next build` (see package.json) so public/data/ always
// reflects the latest data/ output, including files regenerated by build:mortality
// during the Railway build.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "data");
const DEST = path.join(ROOT, "public", "data");

const FILES = [
  "admin1-10m.json",
  "causes.json",
  "density-grid.json",
  "mortality-age-sex.json",
  "nuts2-20m.json",
  "rate-grid.json",
  "sample-personas.json",
  "seasonality-unified.json",
  "seasonality.json",
  "seasonality-loo-validation.json",
  "seasonality-proxies.json",
  "seasonality-subnational.json",
  "seasonality-subnational-loo.json",
  "seasonality-climate-fallback.json",
  "subnational-cdr.json",
];

fs.mkdirSync(DEST, { recursive: true });

for (const f of FILES) {
  const src = path.join(SRC, f);
  if (!fs.existsSync(src)) {
    console.warn(`sync-data: skipping missing ${f}`);
    continue;
  }
  fs.copyFileSync(src, path.join(DEST, f));
}
